spring:
  flyway:
    enabled: false

logging:
  level:
    org.flywaydb.core.internal.resource: DEBUG


env:
  sourceDatabase:
    url: jdbc:postgresql://localhost:5433/source_db
    username: clerk_kent
    password: ihatemyjob
    driver: org.postgresql.Driver
    migrationPath: "filesystem:./migrations/source"
  targetDatabase:
    url: jdbc:postgresql://localhost:5434/target_db
    username: MAGALUFS
    password: moneymoneymoneey
    driver: org.postgresql.Driver
    migrationPath: "filesystem:./migrations/target"
