version: '3.7'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=clerk_kent
      - POSTGRES_PASSWORD=ihatemyjob
      - POSTGRES_DB=source_db
    ports:
      - '5433:5432'